#!/bin/bash
set -e
set -o pipefail

RUBY_VERSION=2.1.6

USER=$(whoami)
: ${HOME:="/Users/$USER"}

echo '----> Install xcode command line tools (click "Install")'
xcode-select --install

echo '----> Installing Homebrew'
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install rcmdnk/file/brew-file
brew file set_repo --repo lumoslabs/dotfiles
brew file install

echo '----> Installing ruby $RUBY_VERSION'
rbenv install $RUBY_VERSION
rbenv global $RUBY_VERSION
gem install bundler
rbenv rehash

if [ ! -f "$HOME/.ssh/github-key" ]; then
  echo '----> Create ssh-key'
  mkdir -v "$HOME/.ssh"
  chmod 0700 "$HOME/.ssh"
  ssh-keygen -t rsa -N '' -f "$HOME/.ssh/github-key" -C "$USER@lumoslabs"
fi

echo '----> Clone data-bags repo & install dependencies'
git clone git@github.com:lumoslabs/chef-data-bags ~/workspace/chef-data-bags
cd ~/workspace/chef-data-bags && bundle install

echo '----> Writing memory executable to bin/'
tee ~/bin/memory <<EOF
#!/bin/bash
# specify bundle_gemfile to speed up load times
BUNDLE_GEMFILE="$HOME/workspace/chef-data-bags/Gemfile" bundle exec ruby $HOME/workspace/chef-data-bags/bin/memory \$*
EOF
chmod +x ~/bin/memory

echo '----> Writing up-to-date knife.rb file'
tee ~/.chef/knife.rb <<EOF
chef_dir        = "#{ENV['HOME']}/.chef"
chef_repo       = "#{ENV['HOME']}/workspace/chef-repo"
chef_server_url = ENV['CHEF_SERVER_URL'] || "https://chef-aws.lumoslabs.com/organizations/lumoslabs"

cache_type               "BasicFile"
chef_server_url          chef_server_url
client_key               "#{chef_dir}/$USER"
cache_options            path: "#{chef_dir}/checksums"
cookbook_copyright       "Lumos Labs, Inc."
cookbook_email           "ops@lumoslabs.com"
cookbook_path            ["#{chef_repo}/cookbooks"]
data_bag_path            "#{ENV['HOME']}/workspace/chef-data-bags/data_bags"
data_bag_encrypt_version 2
log_level                :info
log_location             STDOUT
node_name                "$USER"
role_path                ["#{chef_repo}/roles"]
trusted_certs_dir        "#{chef_dir}/trusted_certs"
validation_client_name   "lumoslabs-validator"
validation_key           "#{chef_dir}/validation.pem"
verify_api_cert          false
versioned_cookbooks      true

knife[:editor]                = 'vim'
knife[:bootstrap_version]     = "12.5.1"
knife[:secret_file]           = "#{chef_dir}/memory.key"
knife[:aws_access_key_id]     = ENV['AWS_ACCESS_KEY_ID']
knife[:aws_secret_access_key] = ENV['AWS_SECRET_ACCESS_KEY']
knife[:region]                = 'us-east-1'
EOF
